name: Playwright Tests
on:
  pull_request:
     branches: [ master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30